name: ImagesearchExample
attributes:
  ORGANIZATIONNAME: 엄기철
include:
  - Package.yml
  - ImageSearchExample.yml
configs:
  debug: debug
  release: release
options:
   deploymentTarget:
     iOS: 12.0
   createIntermediateGroups: true
schemes:
  ImageSearchExample:
    build:
      targets:
        ImagesearchExample: all